name: Daily Data Collection

on:
  schedule:
    - cron: '0 9 * * *'  # This will run daily at 9 AM UTC

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas

      - name: Run Data Collection
        run: python data_collection.py

      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add data/weather_data.csv
          git commit -m "Update weather data"
          git push
